agent:
  id: mongo-agent-01
  environment: prod

mongo:
  uri: mongodb://localhost:27017/?replicaSet=rs0
  slow_ms: 500

logs:
  mongod_log: /var/log/mongodb/mongod.log

intervals:
  host_metrics: 300
  mongo_metrics: 900
  index_inventory: 86400
  package_inventory: 86400
  send_batch: 60

aggregator:
  url: http://jump-server:8080/ingest
  timeout: 5
